package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.File;
import java.io.IOException;

import domain.Users;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

public class GUIEditUserController {
	@FXML
	private Button btnConfirm;
	@FXML
	private Button ButtonReturn;
	@FXML
	private Label lbIdentification;
	@FXML
	private TextField tfName;
	@FXML
	private TextField tfId;
	@FXML
	private TextField TFPassword;
	@FXML
	private TextField tfIdentification;
	@FXML
	private ImageView ivImage;
	@FXML
	private Button btnEditImage;
	@FXML
	private Label LNULL;

	private Users currentUser;
	
	public void initialize() {
		tfName.setText(currentUser.getNameUser());
		tfId.setText(String.valueOf(currentUser.getId()));
		tfIdentification.setText(currentUser.getIdentificationUser());
		
	}
    
	// Método para configurar el usuario actual
    public void setCurrentUser(Users user) {
        this.currentUser = user;
    }
	// Event Listener on Button[#btnConfirm].onAction
	@FXML
	public void btnConfirmAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ButtonReturn].onAction
	@FXML
	public void ButtonReturnAction(ActionEvent event) {
    	try {
	        // Cargar el archivo FXML
	        FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIMenuAdmin.fxml"));
	        Parent root = loader.load();
	        Scene scene = new Scene(root);
	        Stage stage = new Stage();
	        stage.setScene(scene);
	        stage.setTitle("Editar Perfil");
	        stage.show();
	        Stage currentStage = (Stage) ButtonReturn.getScene().getWindow();
	        currentStage.close(); 
	        
	    } catch (IOException e) {
	        e.printStackTrace();
	        System.out.println("Error al abrir GUIEditUser.fxml: " + e.getMessage());
	    }
	}
	// Event Listener on Button[#btnEditImage].onAction
	@FXML
	public void btnEditImageAction(ActionEvent event) {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Seleccionar Imagen");

        FileChooser.ExtensionFilter imageFilter = new FileChooser.ExtensionFilter("Archivos de Imagen", "*.png", "*.jpg", "*.jpeg");
        fileChooser.getExtensionFilters().add(imageFilter);

        // Mostrar el explorador de archivos y obtener el archivo seleccionado
        File file = fileChooser.showOpenDialog(new Stage());

        if (file != null) {
            // Convertir el archivo en una imagen y mostrarla en el ImageView
            Image image = new Image(file.toURI().toString());
            ivImage.setImage(image);
        }
	}
	
	public void loadDataUser() {
		
	}
}
